import { NextResponse } from 'next/server'
import { execSync } from 'child_process'

// Supabase integration — replace with your project values
// Get free credentials at supabase.com
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://your-project.supabase.co'
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'your-anon-key'

// GitHub token for creating issues (optional)
const GITHUB_TOKEN = process.env.GITHUB_TOKEN

// Formspree form ID — get free at https://formspree.io
// Set in Vercel: vercel env add FORMSPREE_FORM_ID
const FORMSPREE_FORM_ID = process.env.FORMSPREE_FORM_ID

export async function POST(request) {
  try {
    const body = await request.json()
    const { name, email, project, tier, description, timeline, notes } = body

    // Validate required fields
    if (!name || !email || !description) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Always log to console (visible in Vercel logs)
    console.log('📬 NEW LEAD:', JSON.stringify({
      name, email, project, tier,
      description: description.substring(0, 100) + '...',
      timeline, notes,
      time: new Date().toISOString()
    }, null, 2))

    // Try to forward to Formspree for email notification (if configured)
    if (FORMSPREE_FORM_ID) {
      try {
        await fetch(`https://formspree.io/f/${FORMSPREE_FORM_ID}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
          body: JSON.stringify({ name, email, tier, timeline, project, description, notes }),
        })
        console.log('✅ Formspree notification sent')
      } catch (e) {
        console.error('Formspree error:', e.message)
      }
    }

    // Try to save to Supabase if configured
    const useSupabase = SUPABASE_URL !== 'https://your-project.supabase.co'

    if (useSupabase) {
      try {
        await fetch(`${SUPABASE_URL}/rest/v1/leads`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'apikey': SUPABASE_ANON_KEY,
            'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
            'Prefer': 'return=representation'
          },
          body: JSON.stringify({
            name, email, project_type: project, tier, description, timeline, notes,
            status: 'new', submitted_at: new Date().toISOString()
          })
        })
      } catch (e) {
        console.error('Supabase error:', e.message)
      }
    }

    // Try to create GitHub issue if token is configured
    if (GITHUB_TOKEN) {
      try {
        const issueBody = `
## Lead Information

**Name:** ${name}
**Email:** ${email}
**Tier:** ${tier}
**Project Type:** ${project}
**Timeline:** ${timeline}
**Description:** ${description}
**Notes:** ${notes || 'None'}

**Submitted:** ${new Date().toISOString()}

---

## Status
- [ ] Initial review
- [ ] Scope confirmed  
- [ ] Payment link sent
- [ ] Payment received
- [ ] In progress
- [ ] Delivered

---
*Auto-generated by Built By AI*
        `.trim().replace(/"/g, '\\"').replace(/\n/g, '\\n')

        const title = `[LEAD] ${name} — ${tier} tier`
        execSync(
          `gh issue create --repo claudiaclawdbot/built-by-ai --title "${title}" --body "${issueBody}" --label "lead"`,
          { encoding: 'utf8', env: { ...process.env, GITHUB_TOKEN } }
        )
        console.log('✅ GitHub issue created for lead:', name)
      } catch (e) {
        console.error('GitHub issue error:', e.message)
      }
    }

    return NextResponse.json({ 
      success: true,
      message: 'Lead received. We\'ll be in touch within 24 hours.' 
    })
  } catch (error) {
    console.error('Form submission error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
