#!/usr/bin/env node
/**
 * Built By AI — Lead Tracker
 * 
 * Uses GitHub Issues to track leads (no external database needed)
 * 
 * Usage:
 *   GITHUB_TOKEN=ghp_xxx node scripts/create-lead.js "Name" "email@example.com" "Basic" "Landing page"
 */

const { execSync } = require('child_process')

const [,, name, email, tier, projectType, description] = process.argv

if (!name || !email || !tier || !projectType) {
  console.error('Usage: node scripts/create-lead.js "Name" "email@example.com" "Basic" "Landing page" "description"')
  process.exit(1)
}

const title = `[LEAD] ${name} — ${tier} tier`
const body = `
## Lead Information

**Name:** ${name}
**Email:** ${email}
**Tier:** ${tier}
**Project Type:** ${projectType}
**Description:** ${description || 'N/A'}

**Submitted:** ${new Date().toISOString()}

---

## Status
- [ ] Initial review
- [ ] Scope confirmed
- [ ] Payment link sent
- [ ] Payment received
- [ ] In progress
- [ ] Delivered
- [ ] revisions remaining

## Notes
<!-- Add notes here -->

---
*Auto-generated by Built By AI lead tracker*
`.trim()

try {
  // Create GitHub issue in the built-by-ai repo
  const result = execSync(
    `gh issue create --repo claudiaclawdbot/built-by-ai --title "${title}" --body "${body.replace(/"/g, '\\"').replace(/\n/g, '\\n')}" --label "lead"`,
    { encoding: 'utf8' }
  )
  console.log('✅ Lead created:', result.trim())
} catch (err) {
  console.error('❌ Failed to create GitHub issue:', err.message)
  console.error('   Make sure gh CLI is authenticated: gh auth login')
  process.exit(1)
}
